"""Shared honesty vocabulary so 'exploratory' vs 'validated' reads consistently
across the app. Strings only — the tested seam; panels build the QLabels."""

EXPLORATORY = 'exploratory'
VALIDATED = 'validated'
AGREEMENT_NOTE = 'agent agreement varies per run, not a calibrated probability'


def consensus_note() -> str:
    """Italic note under the swarm consensus number."""
    return f'{EXPLORATORY} · {AGREEMENT_NOTE}'


def interact_caption() -> str:
    """One-line caption for the Ask-an-Agent tab."""
    return 'Answers are exploratory — generated by local agents, not validated.'
